require 'rubygems'
Gem::manage_gems
require 'rake/gempackagetask'
require 'rake/testtask'
require 'rake/clean'

CLEAN.include("pkg")

# Gemspec reference - http://rubygems.org/read/chapter/20
spec = Gem::Specification.new do |s|
  s.name = "information_card"
  s.version = "0.1.0"
  s.author = "Joe Poon, Jason Sallis"
  s.email = "informationcard-users@rubyforge.org"
  s.homepage = "http://informationcardruby.com"
  s.platform = Gem::Platform::RUBY
  s.summary = "A library for processing information cards"
  s.files = FileList["lib/**/*", "docs/**/*", "test/**/*", "Rakefile", "LICENSE", "CHANGELOG"].exclude("rdoc").to_a
  s.require_path = "lib"
  s.autorequire = "information_card"
  s.has_rdoc = true
  s.extra_rdoc_files = ["README"]  
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/*test.rb"]
  t.verbose = true
end

task :default => [:test]
